######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 09:20:51 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += SCWindow.h
SOURCES += SCWindow.cpp
