headers = 'scene.h'
sources = 'main.c scene.c'

Program('main', sources.split(),
        CFLAGS=['-I/usr/include/SDL', '-Wall', '-Wextra', '-std=c99'],
        LIBS=['GL', 'GLU', 'SDL', 'freetype'])

