headers = 'arcomage.h menu.h scene.h FreeType.h'
sources = 'main.c menu.c scene.c FreeType.cpp'

Program('arcomage', sources.split(),
        CFLAGS=['-I/usr/include/SDL', '-Wall', '-Wextra', '-std=c99'],
        LIBS=['GL', 'GLU', 'SDL', 'freetype'])

