######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 23 18:35:43 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Calendar.h
SOURCES += Calendar.cpp main.cpp
