######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 16 12:15:14 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
