######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 23 09:01:29 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TrayTest.h
SOURCES += main.cpp TrayTest.cpp
