headers = 'basic_unit.h giel.h giel_lua.h'
sources = 'basic_unit.c giel_lua.c giel.c'

Program('giel', sources.split(),
        CFLAGS=['-I/usr/include/SDL', '-std=c99'],
        LIBS=['GL', 'GLU', 'SDL', 'lua'])

